### ISSUE TITLE
dtoverlay gpioled not working properly

### ISSUE THREAD

**Issue by bobbyrana** [raspberrypi/Raspberry-Pi-OS-64bit#207] opened 2022-02-09 21:28 UTC
cpu trigger just keeps the led on 
sometimes does not even work from command line.

**Comment by pelwell** [comment] 2022-02-10 10:48
The `gpio-led` overlay does what it is supposed to do. However, the `cpu` trigger doesn't work - it does work on the 32-bit kernel.

**Comment by pelwell** [comment] 2022-02-10 10:59
Which makes this a duplicate of https://github.com/raspberrypi/linux/issues/4425.

**Closed by pelwell** 2022-02-10 10:59 UTC
