### ISSUE TITLE
the touch input with the official touchscreen is inaccurate

### ISSUE THREAD

**Issue by Sieger1004** [raspberrypi/Raspberry-Pi-OS-64bit#59] opened 2020-06-18 06:09 UTC
The  and y coordinates of the touch input are doubled. in the top left corner its more or less accurate, but touched in the middle it thinks I touched the bottom right corner.

**Comment by Sieger1004** [comment] 2020-06-18 06:11
*Edit:
After a reinstall only the x coordinate is doubled using the touchscreen

**Comment by lurch** [comment] 2020-06-18 09:51
Duplicate of #8 ?

**Closed** 2020-06-18 13:25 UTC
