### ISSUE TITLE
Install language failed

### ISSUE THREAD

**Issue by ss8688** [raspberrypi/Raspberry-Pi-OS-64bit#34] opened 2020-06-02 13:38 UTC
Failed to install Chinese language when initialize

**Comment by ghollingworth** [comment] 2020-06-03 07:42
Can you provide any instructions to follow to reproduce this?

**Comment by ss8688** [comment] 2020-06-03 07:47
Choose China  Chainese   Shanghai

**Comment by ss8688** [comment] 2020-06-03 07:50
Choose  China   Chinese   Shanghai

**Comment by lurch** [comment] 2020-06-03 09:07
Sounds like this might be referring to piwiz? ping @spl237 

@ss8688 Is this a problem specifically with the 64-bit Raspberry Pi OS, or does it also affect the 32-bit version?

**Comment by spl237** [comment] 2020-06-03 09:09
That sounds like piwiz; I can't think of any reason why language support should differ between 32 and 64 bit. It might just be that not very much of the GUI has had Chinese translations supplied, or that the Chinese fonts aren't installed.

**Comment by ss8688** [comment] 2020-06-03 09:46
Armhf vertion work well.Only affect arm64 version

**Comment by spl237** [comment] 2020-06-03 12:32
Just tried the settings above, and I got what looked like Chinese to me - 
![2020-06-03-203022_1920x1080_scrot](https://user-images.githubusercontent.com/10401149/83636823-84398780-a59e-11ea-8f55-111c20a99ca3.png)

There is an error when the wizard installs some of the Chinese fonts, but even with that, I was getting Chinese characters in the menus, as shown.

**Comment by spl237** [comment] 2020-06-03 12:43
Ah - sorry, reading again I think the OP was referring to the install error message, not that Chinese didn't actually work! 

I'll see if I can find out why those packages are not available in 64-bit; it looked to me that they were dependent on some Qt libraries which don't exist for 64-bit.

**Comment by spl237** [comment] 2020-06-03 12:50
OK, I know what the problem is; it's an issue with PackageKit trying to install both an armhf and an arm64 version of a package; I had to fix the same issue in Recommended Software. I'll port that fix across to the wizard.

**Comment by spl237** [comment] 2020-06-03 14:20
Fixed - will be included in next update of wizard.

Can someone with the relevant permissions please close this issue?

**Closed** 2020-06-03 15:28 UTC

**Comment by ss8688** [comment] 2020-06-03 15:34
Close now
